name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Remove stopped containers
      run: sudo docker container prune -f

    - name: Remove unused images
      run: sudo docker image prune -a -f

    - name: Remove unused volumes
      run: sudo docker volume prune -f

    - name: Remove unused networks
      run: sudo docker network prune -f

    - name: Delete Unnecessary Files
      run: sudo rm -rf /var/log/* 

    - name: Pull Docker image
      run: sudo docker pull mklu0611/my-project:latest
    - name: Delete Old docker container
      run: sudo docker rm -f my-project-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name my-project-container mklu0611/my-project